services:
  mysql:
    image: mysql:8.0
    container_name: API-Container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
    - 3306:3306
    volumes:
    - my-db:/var/lib/mysql

volumes:
  my-db:

